/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null } |
  { 'accepted' : null };
export interface JobPosting {
  'id' : bigint,
  'title' : string,
  'salary' : [] | [bigint],
  'jobType' : JobType,
  'postedDate' : Time,
  'description' : string,
  'isActive' : boolean,
  'author' : Principal,
  'company' : string,
  'skills' : string,
  'location' : string,
}
export type JobType = { 'internship' : null } |
  { 'fullTime' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'name' : string,
  'role' : UserRole,
  'company' : [] | [string],
  'skills' : string,
  'location' : string,
}
export type UserRole = { 'employer' : null } |
  { 'jobSeeker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createJob' : ActorMethod<
    [string, string, string, string, [] | [bigint], JobType, string],
    bigint
  >,
  'createProfile' : ActorMethod<
    [UserRole, string, string, string, string, [] | [string]],
    undefined
  >,
  'getCallerProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJob' : ActorMethod<[bigint], undefined>,
  'searchJobs' : ActorMethod<[string], Array<JobPosting>>,
  'unsaveJob' : ActorMethod<[bigint], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateJobStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];