/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobType = IDL.Variant({
  'internship' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'employer' : IDL.Null,
  'jobSeeker' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'company' : IDL.Opt(IDL.Text),
  'skills' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'salary' : IDL.Opt(IDL.Nat),
  'jobType' : JobType,
  'postedDate' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'author' : IDL.Principal,
  'company' : IDL.Text,
  'skills' : IDL.Text,
  'location' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        JobType,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createProfile' : IDL.Func(
      [UserRole, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJob' : IDL.Func([IDL.Nat], [], []),
  'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(JobPosting)], ['query']),
  'unsaveJob' : IDL.Func([IDL.Nat], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateJobStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'internship' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'employer' : IDL.Null,
    'jobSeeker' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'company' : IDL.Opt(IDL.Text),
    'skills' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'salary' : IDL.Opt(IDL.Nat),
    'jobType' : JobType,
    'postedDate' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'author' : IDL.Principal,
    'company' : IDL.Text,
    'skills' : IDL.Text,
    'location' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          JobType,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createProfile' : IDL.Func(
        [UserRole, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJob' : IDL.Func([IDL.Nat], [], []),
    'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(JobPosting)], ['query']),
    'unsaveJob' : IDL.Func([IDL.Nat], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateJobStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };